<a href="https://colab.research.google.com/github/ShahnawazKakarh/roadmap-to-data-science/blob/master/python/NumPy_in_Depth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creation of numpy arrays from list

1D Array

In [ ]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [ ]:
type(array_from_list)

numpy.ndarray

Tuple to Numpy Array

In [ ]:
array_from_tuple = np.array(1, 2, 3, 4, 5) ## using one less paranthesis of tuple.
print(array_from_tuple)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [ ]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


2D Array in Numpy

In [ ]:
empty_array_2d = np.array([[]])
print(empty_array_2d)

[]


In [ ]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(array_2d)

numpy.ndarray

3d Array in Numpy

In [ ]:
empty_array_3d = np.array([[[]]])
print(empty_array_3d)

[]


In [ ]:
array_3d = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
type(array_3d)

numpy.ndarray

In [ ]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


In [ ]:
array_from_list.ndim

1

In [ ]:
array_from_list.shape

(5,)

# **2D Array**

In [ ]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(array_2d)

numpy.ndarray

In [ ]:
array_2d.ndim

2

In [ ]:
array_2d.shape

(3, 3)

# **3D Array**

In [ ]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6],
                     [7, 8]]])

In [ ]:
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
type(array_3d)

numpy.ndarray

In [ ]:
array_3d.ndim

3

In [ ]:
array_3d.shape

(2, 2, 2)

In [ ]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6],
                     [7, 8]],

                    [[9, 10],
                     [11, 12]]])

In [ ]:
array_3d.shape

(3, 2, 2)

In [ ]:
array_3d = np.array([[[1, 2, 3],
                      [3, 4, 5]],

                     [[5, 6, 7],
                     [7, 8, 9]],

                    [[9, 10, 11],
                     [11, 12, 13]]])

In [ ]:
array_3d.shape

(3, 2, 3)

# **Inhomogeneous shape of the internal submatrix**

In [ ]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6, 7],
                     [7, 8, 9]],

                    [[9, 10, 11],
                     [11, 12, 13]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

In [ ]:
array_3d.dtype

dtype('int64')

In [ ]:
array_ = np.array([5, -7.4, 'a', 7.2])
array_

array(['5', '-7.4', 'a', '7.2'], dtype='<U32')

In [ ]:
array_.dtype

dtype('<U32')

In [ ]:
array_ = np.array([5, -7.4, 7, 8.9])
array_

array([ 5. , -7.4,  7. ,  8.9])

In [ ]:
array_.dtype

dtype('float64')

Itemsize returns the size in bytes of each element in the array

In [ ]:
print("Item size of arr_float: ", array_.itemsize, "bytes")

Item size of arr_float:  8 bytes


data provides a direct buffer to the memory location where the array's data is actually stored

In [ ]:
print("Data buffer", array_.data)

Data buffer <memory at 0x7ba891b1d3c0>


# **Indexing and Slicing in NumPy**

In [ ]:
array_from_list

array([1, 2, 3, 4, 5])

In [ ]:
print(array_from_list[2]) ## index

3


In [ ]:
array_from_list[1:4] ## slicing

array([2, 3, 4])

In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(array_2d[2,2]) ## indexing

9


In [ ]:
print(array_2d[2][2]) ## indexing

9


In [ ]:
array_2d[0:2, 1:] ## slicing

array([[2, 3],
       [5, 6]])

In [ ]:
array_2d[1:, 1:] ## slicing

array([[5, 6],
       [8, 9]])

In [ ]:
array_2d[1:, 0:2] ## slicing

array([[4, 5],
       [7, 8]])

In [ ]:
array_3d

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [11, 12, 13]]])

In [ ]:
print(array_3d[0, 1, 1]) ## indexing

4


In [ ]:
print(array_3d[2, 1, 2]) ## indexing

13


In [ ]:
print(array_3d[1, 1, 1]) ## indexing

8


In [ ]:
print(array_3d[0, 1, 0]) ## indexing

3


In [ ]:
array_3d[0:2, 1, 1:] ## slicing

Task: How slicing operation works internally in 3D array and check on all the arithmetic operations for the numpy array

array_3d[start1:stop1, start2:stop2, start3:stop3]

In [ ]:
array_3d[0:2, 1, 1:]
## here 0:2 means 0,1 (as index takes one value less)
## next is 1 which is our row taking size we are saying we want to take row 1 elements of 0,1
## 1: it means takes 1st index to infinite elements
## so, it will print [4,5], [8,9]

array([[4, 5],
       [8, 9]])

# **Methods in Numpy**

# **Arithmetic Operations**

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

#print(a)
#print(b)

print(a + b)  # Addition
print(a - b)  # Subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2) # Power
print(b // a)  # Floor division

[[11 22]
 [33 44]]
[[ -9 -18]
 [-27 -36]]
[[ 10  40]
 [ 90 160]]
[[0.1 0.1]
 [0.1 0.1]]
[[ 1  4]
 [ 9 16]]
[[10 10]
 [10 10]]


Methods in NumPy

Transpose

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Sorting

In [ ]:
import numpy as np
arr_1D = np.array([2, 1, 3, 5, 4, 10, 7, 6])
sorted_arr_1D = np.sort(arr_1D)
print(sorted_arr_1D)

[ 1  2  3  4  5  6  7 10]


In [ ]:
arr_2D = np.array([[3, 2, 1],
                   [6, 5, 4]])
sorted_arr_2D = np.sort(arr_2D)
print(sorted_arr_2D)

[[1 2 3]
 [4 5 6]]


By default sort function, will sort it row wise but if we mention axis is suppose 1 then it will sort in column wise.

axis=0 runs vertically down the columns

axis=1 runs horizontally across the rows

In [ ]:
arr_2D = np.array([[3, 2, 1],
                   [6, 5, 4]])
sorted_arr_2D = np.sort(arr_2D, axis=0)
print(sorted_arr_2D)

[[3 2 1]
 [6 5 4]]


In [ ]:
arr_2D = np.array([[3, 2, 1],
                   [6, 5, 4]])
sorted_arr_2D = np.sort(arr_2D, axis=1)
print(sorted_arr_2D)

[[1 2 3]
 [4 5 6]]


Sort Descending wise

In [ ]:
arr_1D = np.array([2, 1, 3, 5, 4, 10, 7, 6])
arr_1D.sort

<function ndarray.sort>

argsort() - index numbers position is changed wrt sort

In [ ]:
arr_1D_D = np.array([21, 11, 13, 52, 12, 56, 7, 6])
sorted_indices = np.argsort(arr_1D_D)
print(sorted_indices)

[7 6 1 4 2 0 3 5]


In [ ]:
arr_1D

array([ 2,  1,  3,  5,  4, 10,  7,  6])

In [ ]:
sorted_indices = np.argsort(arr_1D)
print(sorted_indices)

[1 0 2 4 3 7 6 5]


Ranking in Recommendation Systems

In [ ]:
similarity_scores = np.array([0.23, 0.85, 0.11, 0.65, 0.91])
sorted_indices = np.argsort(similarity_scores)
print(sorted_indices)

# top 3 recommendations of numbers
# [-3:] will take values from -3 index [2 0 3 1 4] it will pick [3 1 4]
# [::-1] will reverse the array i.e., from [3 1 4] to [4 1 3]
top_3_items = sorted_indices[-3:][::-1]
print(top_3_items)

[2 0 3 1 4]
[4 1 3]


Concatenation Arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [5, 6, 7]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [ ]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [5, 6, 7]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 3 4 5 6]
 [3 4 5 5 6 7]]


Reshape (row, column)

In [ ]:
arr_1D

array([ 2,  1,  3,  5,  4, 10,  7,  6])

In [ ]:
arr_2D = arr_1D.reshape(4, 2)
arr_2D

array([[ 2,  1],
       [ 3,  5],
       [ 4, 10],
       [ 7,  6]])

In [ ]:
arr_2D = arr_1D.reshape(4, 3)
arr_2D

ValueError: cannot reshape array of size 8 into shape (4,3)

In [ ]:
## Flatten the 2D array to 1D array
arr_2D.reshape(-1)

array([ 2,  1,  3,  5,  4, 10,  7,  6])

Two methods

concat -> pandas [deals with labeled-data]

concatenate -> numpy [array-focused]

Split()

In [ ]:
arr_1D

array([ 2,  1,  3,  5,  4, 10,  7,  6])

In [ ]:
split_arr = np.split(arr_1D, 4)
print(split_arr)

[array([2, 1]), array([3, 5]), array([ 4, 10]), array([7, 6])]


Statistical Operations:

Mean, Median and Mode, Standard Deviation, Min, Max, Sum

np.median => Median

np.std => Standard Deviation

np.min => Minimum Value

np.max => Maximum Value

np.sum => Sum

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

mean_all = np.mean(arr)
print(mean_all)

3.5


Data Creation strategy/ways of NumPy Arrays while doing our works!! They are quite handy!

In [ ]:
import numpy as np
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


Zeros, Ones method will create array as per mentioned values.

zeros(2, 3, 4) - 2 arrays, 3 rows and 4 columns.

dtype=(type)

In [ ]:
arr = np.zeros((2, 3, 4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# showing empty sting because 0 is kind of empty sting
arr = np.zeros((2, 3, 4), dtype=str)
print(arr)

[[['' '' '' '']
  ['' '' '' '']
  ['' '' '' '']]

 [['' '' '' '']
  ['' '' '' '']
  ['' '' '' '']]]


In [ ]:
arr = np.zeros((2, 3, 4), dtype=int)
print(arr)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
arr = np.ones((5), dtype=int)
print(arr)

[1 1 1 1 1]


In [ ]:
arr = np.ones((3, 3, 4), dtype=int)
print(arr)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
arr_1 = np.ones((2, 3), dtype=str)
print(arr_1)

[['1' '1' '1']
 ['1' '1' '1']]


full(size, value)

In [ ]:
arr_1d = np.full(5, 7)
print(arr_1d)

[7 7 7 7 7]


In [1]:
import numpy as np

arr_3d = np.full((2,3,4), 3.14)
print(arr_3d)

[[[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]

 [[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]]


# **dtype='<U1'**

The dtype='<U1' specifies a NumPy data type for an array. This particular dtype indicates the following:

<: This signifies little-endian byte order. This means that the least significant byte of a multi-byte data type is stored at the lowest memory address.

U: This indicates that the data type is a Unicode string.

1: This specifies the size of the string, in this case, a single Unicode character.

Therefore, an array with dtype='<U1' will store each element as a 1-character Unicode string, with little-endian byte order.

In [9]:
arr_full_md = np.full((2,3,4), 20, dtype=str)
arr_full_md

# dtype='<U1' ; Here means how much bits it is entertaining?

array([[['2', '2', '2', '2'],
        ['2', '2', '2', '2'],
        ['2', '2', '2', '2']],

       [['2', '2', '2', '2'],
        ['2', '2', '2', '2'],
        ['2', '2', '2', '2']]], dtype='<U1')

In [10]:
arr_full_md = np.full((2,3,4), 20, dtype='U2')
arr_full_md

array([[['20', '20', '20', '20'],
        ['20', '20', '20', '20'],
        ['20', '20', '20', '20']],

       [['20', '20', '20', '20'],
        ['20', '20', '20', '20'],
        ['20', '20', '20', '20']]], dtype='<U2')

np.eye() = It shows us identity matrix

In [2]:
identity_3_cross_4 = np.eye(3, 4)
print(identity_3_cross_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [3]:
identity_4_cross_4 = np.eye(4, 4)
print(identity_4_cross_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


np.arange(start, stop, step_size)

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 2 elements step size and taking value from 3 to 13.
np.arange(3, 13, 2)

array([ 3,  5,  7,  9, 11])

np.random()

In [12]:
np.random.random(5)

array([0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449])

In [14]:
np.random.random((2, 3)) # It means 3 elements (columns) with 2 elements (rows)

array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985]])

np.seed()

On each iteration, fixed set of elements are return

In [17]:
np.random.seed(42)
np.random.random((2, 3))

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

np.linspace(start, stop, num, endpoint, retstep, dtype)

# Difference between np.arrange() and np.linspace()

np.arrange => return consistent elements on the basis of step size

np.linspace => it will return number of elements on the basis of "num" we will enter, it means it will divide the whole data in such number of elements and will return the elements.

In linspace the stop element value, is inclusive while in np.arrange it is exclusive.

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Transpose: https://leetcode.com/problems/transpose-matrix/description/

Matrix Multiplication: https://www.geeksforgeeks.org/problems/multiply-matrices/1

OR https://leetcode.com/problems/construct-product-matrix/description/

QuickSort

MergeSort

HeapSort